version: "3"

services:
  home-assistant:
    image: homeassistant/home-assistant:latest
    hostname: "hassio"
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
